version: 1.0.{build}
configuration: Release
pull_requests:
  do_not_increment_build_number: true
image:
- Visual Studio 2022
- Ubuntu
dotnet_csproj:
  patch: true
  file: '**\Log4net.Appender.Serilog.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: dotnet restore Source\Log4net.Appender.Serilog.sln
build:
  project: Source\Log4net.Appender.Serilog.sln
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: dotnet test Source\Log4net.Appender.Serilog.Tests\Log4net.Appender.Serilog.Tests.csproj
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - ps: dotnet build Source\Log4net.Appender.Serilog\Log4net.Appender.Serilog.csproj --framework netstandard2.0
  test_script:
  - ps: dotnet test Source\Log4net.Appender.Serilog.Tests\Log4net.Appender.Serilog.Tests.csproj --framework net6.0